import type { Location } from "./types";

// Every Calgary quadrant + named neighbourhood + surrounding city we generate
// location-financing pages for. Each entry carries a handful of unique attributes
// (landmarks, drive-time note, buyer archetype) so generated copy never reads
// templated.

export const LOCATIONS: Location[] = [
  {
    id: "ne-calgary",
    slugFragment: "ne-calgary",
    fullName: "Northeast Calgary",
    shortName: "NE Calgary",
    kind: "calgary-quadrant",
    landmarks: ["Genesis Centre", "Sunridge Mall", "Pacific Place Mall", "YYC airport corridor", "Marlborough Mall"],
    driveTimeNote: "Most NE Calgary buyers commute to airport-adjacent jobs (cargo, hospitality, logistics) or downtown via Deerfoot Trail.",
    buyerArchetype: "Predominantly newcomer households and trades workers; the densest concentration of NewWheels' newcomer applications in the city.",
  },
  {
    id: "se-calgary",
    slugFragment: "se-calgary",
    fullName: "Southeast Calgary",
    shortName: "SE Calgary",
    kind: "calgary-quadrant",
    landmarks: ["Seton", "Mahogany", "Cranston", "South Health Campus", "Quarry Park"],
    driveTimeNote: "SE Calgary buyers commute up Deerfoot or along Glenmore to downtown and the airport; many drive to industrial parks in Foothills.",
    buyerArchetype: "Mix of family households in master-planned communities and shift workers at South Health Campus.",
  },
  {
    id: "sw-calgary",
    slugFragment: "sw-calgary",
    fullName: "Southwest Calgary",
    shortName: "SW Calgary",
    kind: "calgary-quadrant",
    landmarks: ["Westhills", "Aspen Landing", "Glenmore Reservoir", "Mount Royal University", "Chinook Centre"],
    driveTimeNote: "SW Calgary buyers tend to commute downtown via Crowchild or 14th Street; MRU faculty and students concentrate here.",
    buyerArchetype: "Established middle-income households and university faculty; higher proportion of trade-in upgrades.",
  },
  {
    id: "nw-calgary",
    slugFragment: "nw-calgary",
    fullName: "Northwest Calgary",
    shortName: "NW Calgary",
    kind: "calgary-quadrant",
    landmarks: ["University of Calgary", "Foothills Medical Centre", "Market Mall", "Crowfoot Crossing"],
    driveTimeNote: "NW Calgary buyers commute to U of C and Foothills along Crowchild and 16th Avenue.",
    buyerArchetype: "Heavy student and healthcare-worker concentration; first-time buyers and PGWP graduates dominate NewWheels applications here.",
  },
  {
    id: "downtown-calgary",
    slugFragment: "downtown-calgary",
    fullName: "Downtown Calgary",
    shortName: "Downtown",
    kind: "calgary-quadrant",
    landmarks: ["The Plus 15", "Stephen Avenue", "East Village", "Eau Claire", "Bow Tower"],
    driveTimeNote: "Downtown buyers tend to lease for short urban commutes or finance for weekend Rockies trips. Many keep a single household vehicle.",
    buyerArchetype: "Young professionals in towers, hospitality workers, and East Village condo buyers; smaller average loan size, higher trade frequency.",
  },
  {
    id: "forest-lawn",
    slugFragment: "forest-lawn",
    fullName: "Forest Lawn (NE Calgary)",
    shortName: "Forest Lawn",
    kind: "calgary-neighbourhood",
    landmarks: ["International Avenue", "Forest Lawn High School", "Marlborough Park", "International Avenue Business Improvement Area"],
    driveTimeNote: "Direct connection to downtown via 17th Avenue SE; many residents service industrial jobs along the Foothills corridor.",
    buyerArchetype: "Tradespeople and small-business owners recovering from oil downturns; highest concentration of NewWheels' bad-credit applications.",
  },
  {
    id: "marlborough",
    slugFragment: "marlborough",
    fullName: "Marlborough (NE Calgary)",
    shortName: "Marlborough",
    kind: "calgary-neighbourhood",
    landmarks: ["Marlborough Mall", "Sunridge", "Memorial Drive", "Pacific Place"],
    driveTimeNote: "Easy Memorial / 36th Street commute to downtown or airport.",
    buyerArchetype: "Established working-class households; high pre-owned truck demand.",
  },
  {
    id: "falconridge",
    slugFragment: "falconridge",
    fullName: "Falconridge (NE Calgary)",
    shortName: "Falconridge",
    kind: "calgary-neighbourhood",
    landmarks: ["Falconridge Plaza", "Pacific Place Mall", "Northern Hills"],
    driveTimeNote: "Deerfoot-adjacent; quick airport-employment commute.",
    buyerArchetype: "South Asian and Filipino newcomer families; one of the city's densest newcomer-family clusters.",
  },
  {
    id: "saddle-ridge",
    slugFragment: "saddle-ridge",
    fullName: "Saddle Ridge (NE Calgary)",
    shortName: "Saddle Ridge",
    kind: "calgary-neighbourhood",
    landmarks: ["Genesis Centre", "Saddletowne Circle", "Punjabi Bazaar"],
    driveTimeNote: "Stoney Trail loop opens up airport, downtown, and SE commutes.",
    buyerArchetype: "Largest Punjabi household concentration in the city; high family-SUV and Sienna demand.",
  },
  {
    id: "martindale",
    slugFragment: "martindale",
    fullName: "Martindale (NE Calgary)",
    shortName: "Martindale",
    kind: "calgary-neighbourhood",
    landmarks: ["Martindale Boulevard", "Saddle Towne LRT", "Genesis Centre"],
    driveTimeNote: "Blue Line LRT for downtown commutes; Stoney Trail for industrial.",
    buyerArchetype: "Heavily Filipino, Indian, and Pakistani newcomer households; many first-time PR buyers.",
  },
  {
    id: "airdrie",
    slugFragment: "airdrie",
    fullName: "Airdrie",
    shortName: "Airdrie",
    kind: "surrounding-city",
    landmarks: ["Genesis Place", "Bayview", "Coopers Crossing", "CrossIron Mills"],
    driveTimeNote: "20–30 minute QEII commute into NE Calgary or downtown; heavy truck-and-SUV mix.",
    buyerArchetype: "Young families pushed north by Calgary pricing; high family-SUV demand and a growing newcomer cluster in Genesis and Bayside.",
  },
  {
    id: "cochrane",
    slugFragment: "cochrane",
    fullName: "Cochrane",
    shortName: "Cochrane",
    kind: "surrounding-city",
    landmarks: ["Sunset Boulevard", "Heartland", "Bow Valley Trail"],
    driveTimeNote: "Highway 1A or Highway 22 into NW Calgary and U of C; predominantly suburban detached households.",
    buyerArchetype: "Higher-income established families; AWD SUV and pickup demand outpaces sedans by 5×.",
  },
  {
    id: "okotoks",
    slugFragment: "okotoks",
    fullName: "Okotoks",
    shortName: "Okotoks",
    kind: "surrounding-city",
    landmarks: ["Olde Towne", "Air Ranch", "Sheep River"],
    driveTimeNote: "Highway 2 into SW and SE Calgary; busy oil-and-gas commute corridor.",
    buyerArchetype: "Energy-industry families and trades; strong half-ton and three-quarter-ton truck demand.",
  },
  {
    id: "chestermere",
    slugFragment: "chestermere",
    fullName: "Chestermere",
    shortName: "Chestermere",
    kind: "surrounding-city",
    landmarks: ["Chestermere Lake", "Rainbow Falls", "West Creek"],
    driveTimeNote: "Stoney Trail north into NE Calgary and the airport; growing eastern suburb.",
    buyerArchetype: "Young families in master-planned lakefront communities; family SUVs and crossover demand dominate.",
  },
  {
    id: "strathmore",
    slugFragment: "strathmore",
    fullName: "Strathmore",
    shortName: "Strathmore",
    kind: "surrounding-city",
    landmarks: ["Strathmore Centre", "Trans-Canada corridor"],
    driveTimeNote: "Trans-Canada highway commute into SE Calgary; agricultural and trades base.",
    buyerArchetype: "Farm-and-trades households; pickup truck demand is the highest of any surrounding city by share.",
  },
  {
    id: "high-river",
    slugFragment: "high-river",
    fullName: "High River",
    shortName: "High River",
    kind: "surrounding-city",
    landmarks: ["Centre Street", "Cargill plant", "George Lane Park"],
    driveTimeNote: "Highway 2 into SW Calgary; heavily Cargill-shift and agricultural buyer base.",
    buyerArchetype: "Shift workers and farming families; sub-prime financing demand higher than Calgary average.",
  },
  {
    id: "crossfield",
    slugFragment: "crossfield",
    fullName: "Crossfield",
    shortName: "Crossfield",
    kind: "surrounding-city",
    landmarks: ["Mountain View County", "Crossfield Industrial Park"],
    driveTimeNote: "QEII commute south to Airdrie and Calgary; semi-rural lifestyle vehicle demand.",
    buyerArchetype: "Tradespeople, small-acreage owners; 4×4 demand higher than urban average.",
  },
  {
    id: "carstairs",
    slugFragment: "carstairs",
    fullName: "Carstairs",
    shortName: "Carstairs",
    kind: "surrounding-city",
    landmarks: ["Mountain View Credit Union", "QEII corridor"],
    driveTimeNote: "QEII commute into Airdrie, NE Calgary, and the airport; mostly long-haul commuters.",
    buyerArchetype: "Long-commute workers prioritising fuel economy plus AWD for winter highway.",
  },
];

export function locationBySlugFragment(fragment: string): Location | undefined {
  return LOCATIONS.find(l => l.slugFragment === fragment);
}
