import type { VehicleMake } from "./types";

export const VEHICLE_MAKES: VehicleMake[] = [
  {
    id: "toyota",
    slugFragment: "toyota",
    fullName: "Toyota",
    shortName: "Toyota",
    financeProgram: "Toyota Financial Services + Toyota Newcomer Program",
    brandNote: "Best-in-class resale, the most reliable engines in Canada, and a deep newcomer-friendly finance arm.",
    calgaryNote: "Calgary's #1 financed make through NewWheels. RAV4, Corolla, and Camry move the fastest; Tacoma waits 2–3 months for new inventory.",
    topModels: ["RAV4", "Camry", "Corolla", "Highlander", "Tacoma", "Tundra", "4Runner", "Sienna"],
  },
  {
    id: "honda",
    slugFragment: "honda",
    fullName: "Honda",
    shortName: "Honda",
    financeProgram: "Honda Financial Services + Honda New to Canada program",
    brandNote: "Bulletproof reliability and the strongest used-vehicle pricing in the segment.",
    calgaryNote: "Civic and CR-V dominate Calgary first-time and newcomer buyers. The Pilot and Odyssey serve the multi-generational South Asian and Filipino households in Saddle Ridge and Martindale.",
    topModels: ["Civic", "CR-V", "Accord", "HR-V", "Pilot", "Odyssey", "Ridgeline"],
  },
  {
    id: "ford",
    slugFragment: "ford",
    fullName: "Ford",
    shortName: "Ford",
    financeProgram: "Ford Credit + commercial fleet programs",
    brandNote: "Canada's best-selling pickup. F-150 owns the half-ton segment.",
    calgaryNote: "Largest pickup-truck base in NewWheels' financed inventory. F-150 SuperCrews and Rangers route through Calgary trades and oil-and-gas; the Maverick is the fastest-growing newcomer pick.",
    topModels: ["F-150", "Ranger", "Maverick", "Escape", "Bronco", "Explorer", "Edge"],
  },
  {
    id: "chevrolet",
    slugFragment: "chevrolet",
    fullName: "Chevrolet",
    shortName: "Chevy",
    financeProgram: "GM Financial",
    brandNote: "Strong truck and SUV lineup with deep GM Financial incentives during quarter-ends.",
    calgaryNote: "Silverado and Trax outsell sedans 4:1 in Calgary. Bolt EV is a NewWheels favourite for budget-conscious EV buyers.",
    topModels: ["Silverado 1500", "Equinox", "Trax", "Trailblazer", "Tahoe", "Suburban", "Bolt EV"],
  },
  {
    id: "nissan",
    slugFragment: "nissan",
    fullName: "Nissan",
    shortName: "Nissan",
    financeProgram: "Nissan Canada Finance + dedicated Newcomer Program",
    brandNote: "Most newcomer-friendly OEM in Canada. We have a direct dealer relationship for new Nissans.",
    calgaryNote: "Brand-new Nissans through NewWheels frequently approve at newcomer rates that beat third-party sub-prime. Rogue, Kicks, Sentra, and Armada are the top sellers.",
    topModels: ["Rogue", "Kicks", "Sentra", "Pathfinder", "Armada", "Frontier", "Murano"],
  },
  {
    id: "hyundai",
    slugFragment: "hyundai",
    fullName: "Hyundai",
    shortName: "Hyundai",
    financeProgram: "Hyundai Capital + Hyundai Newcomer Program",
    brandNote: "Class-leading warranty (5-year / 100,000 km) and aggressive newcomer-program rates.",
    calgaryNote: "Tucson and Elantra are the top first-time buyer and newcomer picks. IONIQ 5 leads the entry-EV segment.",
    topModels: ["Tucson", "Elantra", "Santa Fe", "Kona", "Palisade", "IONIQ 5", "IONIQ 6"],
  },
  {
    id: "kia",
    slugFragment: "kia",
    fullName: "Kia",
    shortName: "Kia",
    financeProgram: "Kia Finance",
    brandNote: "Same chassis families as Hyundai with stronger styling and a similarly competitive warranty.",
    calgaryNote: "Telluride is the most-requested 3-row SUV for Calgary families. Sportage and Forte serve first-time buyers and PGWP graduates.",
    topModels: ["Sportage", "Forte", "Sorento", "Telluride", "Soul", "EV6"],
  },
  {
    id: "mazda",
    slugFragment: "mazda",
    fullName: "Mazda",
    shortName: "Mazda",
    financeProgram: "Mazda Finance",
    brandNote: "Best driving feel in the mainstream segment; CX-5 and CX-50 lead handling vs CR-V and RAV4.",
    calgaryNote: "Higher-income SW Calgary and NW Calgary buyers over-index on Mazda. AWD comes standard on most trims, which Calgary winters reward.",
    topModels: ["CX-5", "CX-50", "Mazda3", "CX-90", "CX-30"],
  },
  {
    id: "dodge",
    slugFragment: "dodge",
    fullName: "Dodge",
    shortName: "Dodge",
    financeProgram: "Stellantis Financial Services Canada",
    brandNote: "Performance pricing and aggressive cash incentives during quarter-ends.",
    calgaryNote: "Charger and Challenger demand outpaces the Canadian average — Calgary's trades and oil-and-gas culture rewards V8s.",
    topModels: ["Charger", "Challenger", "Durango", "Hornet"],
  },
  {
    id: "jeep",
    slugFragment: "jeep",
    fullName: "Jeep",
    shortName: "Jeep",
    financeProgram: "Stellantis Financial Services Canada",
    brandNote: "Off-road heritage and the most weather-capable mid-size SUV lineup.",
    calgaryNote: "Wrangler and Grand Cherokee are the highest-financed Jeeps in Calgary; Rockies-adjacent buyers (Cochrane, NW) skew Jeep-heavy.",
    topModels: ["Wrangler", "Grand Cherokee", "Compass", "Cherokee", "Gladiator"],
  },
  {
    id: "ram",
    slugFragment: "ram",
    fullName: "RAM",
    shortName: "RAM",
    financeProgram: "Stellantis Financial Services Canada",
    brandNote: "Best half-ton interior in the segment; the only pickup with coil-spring rear suspension.",
    calgaryNote: "RAM 1500 outsells the Silverado by ~10% in Calgary trades; the 2500/3500 Heavy Duty serve oil-and-gas and gravel-hauling households around Strathmore and High River.",
    topModels: ["1500", "2500", "3500", "ProMaster"],
  },
  {
    id: "gmc",
    slugFragment: "gmc",
    fullName: "GMC",
    shortName: "GMC",
    financeProgram: "GM Financial",
    brandNote: "Same drivetrains as Chevrolet with a more premium interior and Denali trim hierarchy.",
    calgaryNote: "Sierra Denali and Yukon Denali dominate the SW Calgary executive-truck segment.",
    topModels: ["Sierra 1500", "Sierra 2500", "Yukon", "Yukon XL", "Terrain", "Acadia"],
  },
  {
    id: "subaru",
    slugFragment: "subaru",
    fullName: "Subaru",
    shortName: "Subaru",
    financeProgram: "Subaru Financial Services",
    brandNote: "Standard symmetrical AWD on every model — Calgary winter's preferred drivetrain.",
    calgaryNote: "Outback, Forester, and Crosstrek lead Cochrane and SW Calgary AWD demand; the Wilderness trim is a NewWheels favourite for Rockies-adjacent buyers.",
    topModels: ["Outback", "Forester", "Crosstrek", "Ascent", "Impreza"],
  },
  {
    id: "volkswagen",
    slugFragment: "volkswagen",
    fullName: "Volkswagen",
    shortName: "VW",
    financeProgram: "Volkswagen Finance",
    brandNote: "European driving feel with a Canadian-spec winter package and 4Motion AWD on most trims.",
    calgaryNote: "Tiguan and Atlas serve growing families; Jetta is a steady first-time-buyer pick.",
    topModels: ["Tiguan", "Jetta", "Atlas", "Atlas Cross Sport", "Taos", "ID.4"],
  },
  {
    id: "bmw",
    slugFragment: "bmw",
    fullName: "BMW",
    shortName: "BMW",
    financeProgram: "BMW Financial Services Canada",
    brandNote: "Driving feel and luxury that no mainstream make matches.",
    calgaryNote: "X3 and X5 dominate established SW Calgary and NW Calgary households. Used-CPO BMW financing is the most common NewWheels BMW pathway for newcomers.",
    topModels: ["X3", "X5", "X1", "3 Series", "5 Series", "X7"],
  },
  {
    id: "mercedes-benz",
    slugFragment: "mercedes",
    fullName: "Mercedes-Benz",
    shortName: "Mercedes",
    financeProgram: "Mercedes-Benz Financial Canada",
    brandNote: "Premium interiors and the strongest brand recognition in the luxury segment.",
    calgaryNote: "GLC, GLE, and C-Class lead Calgary luxury financing. Used Sprinter financing is the fastest-growing commercial segment for NewWheels.",
    topModels: ["GLC", "GLE", "C-Class", "E-Class", "GLA", "Sprinter"],
  },
  {
    id: "audi",
    slugFragment: "audi",
    fullName: "Audi",
    shortName: "Audi",
    financeProgram: "Audi Finance Canada",
    brandNote: "quattro AWD on most trims; an excellent winter luxury choice.",
    calgaryNote: "Q5 and Q7 demand is steady; Mandarin-speaking and South Asian household segments over-index on the e-tron and Q8.",
    topModels: ["Q5", "Q7", "Q3", "A4", "A6", "e-tron"],
  },
];

export function vehicleMakeBySlugFragment(fragment: string): VehicleMake | undefined {
  return VEHICLE_MAKES.find(m => m.slugFragment === fragment);
}
