import type { VehicleModel } from "./types";

// Top financed models in Calgary. Used to generate `/{make}-{model}-financing-calgary`
// pages with Vehicle schema.

export const VEHICLE_MODELS: VehicleModel[] = [
  {
    id: "toyota-rav4",
    slugFragment: "toyota-rav4",
    fullName: "Toyota RAV4",
    shortName: "RAV4",
    make: "toyota",
    bodyType: "SUV",
    fuelType: "Gasoline + Hybrid options",
    driveWheelConfig: "AWD",
    modelDate: "2024",
    approxPriceRange: [35000, 52000],
    calgaryAngle:
      "The single most-financed vehicle through NewWheels. The RAV4 Hybrid AWD handles -30°C Calgary mornings where pure EVs lose range, and Toyota's newcomer program approves PGWP and PR holders at rates that beat third-party sub-prime by 3–5 points.",
  },
  {
    id: "ford-f150",
    slugFragment: "ford-f150",
    fullName: "Ford F-150",
    shortName: "F-150",
    make: "ford",
    bodyType: "Pickup truck",
    fuelType: "Gasoline + Hybrid + EV (Lightning)",
    driveWheelConfig: "4×4",
    modelDate: "2024",
    approxPriceRange: [50000, 95000],
    calgaryAngle:
      "Calgary's #1 financed pickup. Ford Credit's commercial fleet pricing routinely beats independent half-ton sub-prime quotes for trades and oil-and-gas applicants. The PowerBoost hybrid is the fastest-growing F-150 trim for NewWheels Forest Lawn and Strathmore buyers.",
  },
  {
    id: "honda-crv",
    slugFragment: "honda-crv",
    fullName: "Honda CR-V",
    shortName: "CR-V",
    make: "honda",
    bodyType: "SUV",
    fuelType: "Gasoline + Hybrid options",
    driveWheelConfig: "AWD",
    modelDate: "2024",
    approxPriceRange: [37000, 52000],
    calgaryAngle:
      "Honda's New to Canada program prices the CR-V Hybrid 2–4 points below sub-prime for newcomer households. Calgary multi-generational households consistently rank the CR-V as the #2 family SUV behind the RAV4.",
  },
  {
    id: "hyundai-tucson",
    slugFragment: "hyundai-tucson",
    fullName: "Hyundai Tucson",
    shortName: "Tucson",
    make: "hyundai",
    bodyType: "SUV",
    fuelType: "Gasoline + Hybrid + PHEV options",
    driveWheelConfig: "AWD",
    modelDate: "2024",
    approxPriceRange: [33000, 48000],
    calgaryAngle:
      "Best warranty in the segment (5-year / 100,000 km) and the most aggressive newcomer-program rate sheet of any OEM. Tucson Hybrid AWD is the most-financed Hyundai through NewWheels in NE Calgary.",
  },
  {
    id: "chevrolet-silverado",
    slugFragment: "chevrolet-silverado",
    fullName: "Chevrolet Silverado 1500",
    shortName: "Silverado",
    make: "chevrolet",
    bodyType: "Pickup truck",
    fuelType: "Gasoline + Diesel",
    driveWheelConfig: "4×4",
    modelDate: "2024",
    approxPriceRange: [48000, 90000],
    calgaryAngle:
      "GM Financial's quarter-end incentives on Silverado 1500 Custom and LT trims routinely produce the lowest payment per dollar of any half-ton in Calgary. Heavy demand from oil-and-gas, trades, and small-business owners.",
  },
  {
    id: "toyota-tacoma",
    slugFragment: "toyota-tacoma",
    fullName: "Toyota Tacoma",
    shortName: "Tacoma",
    make: "toyota",
    bodyType: "Pickup truck (mid-size)",
    fuelType: "Gasoline + Hybrid (i-FORCE MAX)",
    driveWheelConfig: "4×4",
    modelDate: "2024",
    approxPriceRange: [45000, 75000],
    calgaryAngle:
      "Longest waitlist of any mid-size truck in Calgary. The Tacoma holds resale better than any competitor; financing through Toyota Financial keeps the rate sheet competitive even on used trucks.",
  },
  {
    id: "ram-1500",
    slugFragment: "ram-1500",
    fullName: "RAM 1500",
    shortName: "RAM 1500",
    make: "ram",
    bodyType: "Pickup truck",
    fuelType: "Gasoline + Hurricane I-6",
    driveWheelConfig: "4×4",
    modelDate: "2024",
    approxPriceRange: [50000, 100000],
    calgaryAngle:
      "Best half-ton interior in the segment. Stellantis Financial Services' Big Horn and Laramie quarter-end cash often beats the Silverado and F-150 by ~$2,500 on Calgary deals.",
  },
  {
    id: "nissan-rogue",
    slugFragment: "nissan-rogue",
    fullName: "Nissan Rogue",
    shortName: "Rogue",
    make: "nissan",
    bodyType: "SUV",
    fuelType: "Gasoline (Variable Compression Turbo)",
    driveWheelConfig: "AWD",
    modelDate: "2024",
    approxPriceRange: [33000, 47000],
    calgaryAngle:
      "Nissan Canada Finance's newcomer program prices Rogue AWD at rates that frequently beat third-party sub-prime by 3–5 points. NewWheels' direct dealer relationship means new Rogues are available without inventory waits.",
  },
  {
    id: "nissan-kicks",
    slugFragment: "nissan-kicks",
    fullName: "Nissan Kicks",
    shortName: "Kicks",
    make: "nissan",
    bodyType: "Crossover",
    fuelType: "Gasoline",
    driveWheelConfig: "FWD",
    modelDate: "2024",
    approxPriceRange: [22000, 30000],
    calgaryAngle:
      "Lowest insurance and lowest monthly payment in the new-Nissan lineup. The most-financed first-vehicle pick for SAIT and MRU graduates.",
  },
  {
    id: "honda-civic",
    slugFragment: "honda-civic",
    fullName: "Honda Civic",
    shortName: "Civic",
    make: "honda",
    bodyType: "Sedan",
    fuelType: "Gasoline + Hybrid options",
    driveWheelConfig: "FWD",
    modelDate: "2024",
    approxPriceRange: [27000, 38000],
    calgaryAngle:
      "Calgary's #1 first-time-buyer pick. Honda Financial Services first-time-buyer programs and Honda's New to Canada program make the Civic the easiest no-Canadian-credit approval in the segment.",
  },
  {
    id: "toyota-corolla",
    slugFragment: "toyota-corolla",
    fullName: "Toyota Corolla",
    shortName: "Corolla",
    make: "toyota",
    bodyType: "Sedan",
    fuelType: "Gasoline + Hybrid options",
    driveWheelConfig: "FWD",
    modelDate: "2024",
    approxPriceRange: [25000, 36000],
    calgaryAngle:
      "Lowest five-year cost of ownership of any sedan in Calgary. Toyota's newcomer program approves Corolla applications with thin Canadian credit at the same rate sheet as established credit.",
  },
  {
    id: "honda-pilot",
    slugFragment: "honda-pilot",
    fullName: "Honda Pilot",
    shortName: "Pilot",
    make: "honda",
    bodyType: "SUV (3 row)",
    fuelType: "Gasoline",
    driveWheelConfig: "AWD",
    modelDate: "2024",
    approxPriceRange: [55000, 70000],
    calgaryAngle:
      "Most-financed three-row family SUV for Calgary South Asian and Filipino households in Saddle Ridge, Martindale, and Skyview.",
  },
  {
    id: "toyota-highlander",
    slugFragment: "toyota-highlander",
    fullName: "Toyota Highlander",
    shortName: "Highlander",
    make: "toyota",
    bodyType: "SUV (3 row)",
    fuelType: "Gasoline + Hybrid",
    driveWheelConfig: "AWD",
    modelDate: "2024",
    approxPriceRange: [55000, 70000],
    calgaryAngle:
      "Highlander Hybrid AWD is NewWheels' top financed three-row hybrid. Best fuel economy of any three-row in Calgary.",
  },
  {
    id: "toyota-sienna",
    slugFragment: "toyota-sienna",
    fullName: "Toyota Sienna",
    shortName: "Sienna",
    make: "toyota",
    bodyType: "Minivan",
    fuelType: "Hybrid only",
    driveWheelConfig: "FWD / AWD",
    modelDate: "2024",
    approxPriceRange: [48000, 70000],
    calgaryAngle:
      "Only hybrid minivan on the Canadian market. Top NewWheels pick for multi-generational households and rideshare drivers seeking the lowest fuel cost per passenger.",
  },
];

export function vehicleModelBySlugFragment(fragment: string): VehicleModel | undefined {
  return VEHICLE_MODELS.find(v => v.slugFragment === fragment);
}
