// POST /api/crm/ai/weekly-briefing — generate and send CEO weekly briefing.

import { NextResponse } from "next/server";
import { readSession } from "@/lib/crm/auth/session";
import { generateWeeklyBriefing } from "@/lib/crm/ai-features";
import { sendEmail } from "@/lib/email/resend";
import { systemEmailWrapper } from "@/lib/email/wrapper";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST() {
  const session = await readSession("crm");
  if (!session || session.subject.kind !== "team" || session.subject.role !== "ceo") {
    return NextResponse.json({ ok: false, error: "forbidden" }, { status: 403 });
  }

  const briefing = await generateWeeklyBriefing();
  if (!briefing) {
    return NextResponse.json({ ok: false, error: "ai_not_configured" });
  }

  // Convert markdown-ish text to HTML paragraphs
  const htmlBody = briefing
    .split("\n\n")
    .filter((p) => p.trim())
    .map((p) => `<p style="margin:0 0 16px;font-size:15px;color:#0A2818;line-height:1.6;">${p.trim()}</p>`)
    .join("");

  const html = systemEmailWrapper(`
    <h1 style="margin:0 0 8px;font-size:22px;font-weight:800;color:#0A2818;">
      Weekly CEO Briefing
    </h1>
    <p style="margin:0 0 20px;font-size:12px;color:#6B7280;">
      ${new Date().toLocaleDateString("en-CA", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
    </p>
    ${htmlBody}
    <p style="margin:24px 0 0;font-size:11px;color:#6B7280;font-style:italic;">
      Generated by NewWheels AI. Data reflects the last 7 days.
    </p>
  `);

  // Send to CEO email (from session)
  const { data: teamMember } = await (await import("@/lib/crm/supabase/server")).getServerSupabase()!
    .from("team_members")
    .select("email")
    .eq("id", session.subject.team_member_id)
    .single();

  if (teamMember?.email) {
    await sendEmail({
      to: teamMember.email as string,
      subject: `NewWheels Weekly Briefing — ${new Date().toLocaleDateString("en-CA")}`,
      html,
      tags: [{ name: "type", value: "weekly_briefing" }],
    });
  }

  return NextResponse.json({ ok: true, briefing });
}
