-- NewWheels CRM + Lead Marketplace — initial schema.
--
-- Everything the platform needs lives in the `nw` schema so the CRM tables
-- never collide with anything that might land in Supabase's `public` schema
-- (auth schema is owned by Supabase). Row-Level-Security policies live in a
-- separate migration so they're easy to review and tweak independently.
--
-- All timestamps are `timestamptz`. All money is integer minor units (cents).
-- All identifiers are UUID v4 generated by Postgres (`gen_random_uuid()`).
--
-- This migration is idempotent so it can be re-run safely during early dev.

create extension if not exists "pgcrypto";
create extension if not exists "citext";

create schema if not exists nw;

-- =====================================================================
-- ENUMS
-- =====================================================================

do $$ begin
  create type nw.team_role as enum (
    'ceo',
    'lead_qualifier',
    'community_outreach',
    'content_seo',
    'bdr',
    'platform_ops',
    'hr'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.lead_status as enum (
    'new',
    'qualifying',
    'qualified',
    'available',
    'sold',
    'expired',
    'unqualified',
    'duplicate'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.lead_tier as enum ('hot', 'warm', 'standard');
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.buyer_kind as enum ('dealer_master', 'dealer_sub', 'individual');
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.buyer_status as enum ('pending_verification', 'active', 'rejected', 'suspended');
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.purchase_status as enum ('pending_payment', 'paid', 'failed', 'refunded_credit');
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.unqualified_reason as enum (
    'uncontactable',
    'fake_information',
    'not_serious_intent',
    'outside_alberta',
    'underage',
    'duplicate_submission',
    'other'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.dispute_status as enum ('open', 'approved_credit', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.verification_decision as enum ('approved', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  create type nw.email_direction as enum ('inbound', 'outbound');
exception when duplicate_object then null; end $$;

-- =====================================================================
-- TEAM / AUTH
-- =====================================================================

create table if not exists nw.team_members (
  id uuid primary key default gen_random_uuid(),
  email citext not null unique,
  display_name text not null,
  role nw.team_role not null,
  team_email citext unique,                 -- e.g. qualifier1@team.newwheels.ca
  active boolean not null default true,
  daily_target int,                          -- e.g. leads-per-day target for Lead Qualifier
  invited_at timestamptz not null default now(),
  first_logged_in_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists team_members_role_idx on nw.team_members(role);
create index if not exists team_members_active_idx on nw.team_members(active);

create table if not exists nw.buyer_accounts (
  id uuid primary key default gen_random_uuid(),
  kind nw.buyer_kind not null,
  status nw.buyer_status not null default 'pending_verification',

  -- contact / identity
  email citext not null unique,
  contact_name text not null,
  phone text,

  -- dealer-specific fields
  business_name text,
  business_address text,
  amvic_licence text,                        -- AMVIC number (required for dealer + individual)

  -- master/sub linkage (null for individuals)
  master_account_id uuid references nw.buyer_accounts(id) on delete cascade,
  invoice_name text,                         -- per-sub invoice override for billing

  -- payment
  stripe_customer_id text,
  default_payment_method_id text,            -- Stripe pm_xxx
  payment_method_status text not null default 'missing',  -- missing | valid | invalid

  -- dealer master budget
  monthly_budget_cents int,                  -- master only; null means no cap
  sub_allocated_budget_cents int,            -- for a sub: portion of master budget
  current_month_spent_cents int not null default 0,
  budget_period_start date not null default date_trunc('month', current_date)::date,

  -- onboarding
  onboarding_completed_at timestamptz,

  -- verification
  verified_at timestamptz,
  verified_by uuid references nw.team_members(id),
  rejection_reason text,
  rejection_decided_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists buyer_accounts_status_idx on nw.buyer_accounts(status);
create index if not exists buyer_accounts_kind_idx on nw.buyer_accounts(kind);
create index if not exists buyer_accounts_master_idx on nw.buyer_accounts(master_account_id);

create table if not exists nw.buyer_verification_docs (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references nw.buyer_accounts(id) on delete cascade,
  -- Storage path inside the private `verification-docs` bucket; never serve
  -- this URL directly — always sign a short-lived URL when CEO reviews.
  storage_path text not null,
  doc_kind text not null,                    -- 'amvic_licence' | 'gov_id' | 'business_doc' | 'other'
  original_filename text,
  mime_type text,
  size_bytes bigint,
  uploaded_at timestamptz not null default now()
);

create index if not exists buyer_verification_docs_buyer_idx on nw.buyer_verification_docs(buyer_id);

create table if not exists nw.verification_decisions (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references nw.buyer_accounts(id) on delete cascade,
  decision nw.verification_decision not null,
  decided_by uuid not null references nw.team_members(id),
  reason text,
  decided_at timestamptz not null default now()
);

create index if not exists verification_decisions_buyer_idx on nw.verification_decisions(buyer_id);

-- Passwordless OTPs. Single use, 10 minute TTL.
create table if not exists nw.auth_otps (
  id uuid primary key default gen_random_uuid(),
  email citext not null,
  code_hash text not null,                   -- SHA-256(code + secret)
  audience text not null,                    -- 'crm' or 'portal'
  expires_at timestamptz not null,
  consumed_at timestamptz,
  attempts smallint not null default 0,
  remember boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists auth_otps_email_idx on nw.auth_otps(email);
create index if not exists auth_otps_expires_idx on nw.auth_otps(expires_at);

-- Sessions. Cookie carries a signed token, this table is the source of truth
-- so we can revoke a session by deleting the row.
create table if not exists nw.sessions (
  id uuid primary key default gen_random_uuid(),
  audience text not null,                    -- 'crm' | 'portal'
  team_member_id uuid references nw.team_members(id) on delete cascade,
  buyer_account_id uuid references nw.buyer_accounts(id) on delete cascade,
  user_agent text,
  ip_address text,
  remember boolean not null default false,
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint sessions_subject_check check (
    (team_member_id is not null and buyer_account_id is null) or
    (team_member_id is null and buyer_account_id is not null)
  )
);

create index if not exists sessions_team_idx on nw.sessions(team_member_id);
create index if not exists sessions_buyer_idx on nw.sessions(buyer_account_id);
create index if not exists sessions_expires_idx on nw.sessions(expires_at);

-- =====================================================================
-- LEADS
-- =====================================================================

create table if not exists nw.leads (
  id uuid primary key default gen_random_uuid(),
  -- form payload
  first_name text not null,
  last_name text not null,
  email citext not null,
  phone text not null,
  source_page text,
  raw_payload jsonb not null default '{}'::jsonb,

  -- pipeline state
  status nw.lead_status not null default 'new',
  duplicate_of uuid references nw.leads(id),

  -- assignment
  assigned_qualifier_id uuid references nw.team_members(id),
  assigned_at timestamptz,

  -- qualification outcome (joined on submission)
  qualified_at timestamptz,
  unqualified_reason nw.unqualified_reason,

  -- scoring + pricing
  score smallint,                            -- 0..100, computed on qualification
  tier nw.lead_tier,
  starting_price_cents int,
  current_price_cents int,
  available_at timestamptz,                  -- when marketplace listing opened
  expires_at timestamptz,                    -- 72h after available_at
  sold_at timestamptz,
  expired_at timestamptz,

  -- relist tracking
  relisted_count smallint not null default 0,
  relisted_at timestamptz,
  relisted_by uuid references nw.team_members(id),

  -- attribution
  source_channel text,                       -- 'facebook_organic' | 'facebook_ads' | 'google_organic' | 'google_ads' | 'whatsapp' | 'direct' | etc.

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_status_idx on nw.leads(status);
create index if not exists leads_tier_idx on nw.leads(tier);
create index if not exists leads_assigned_idx on nw.leads(assigned_qualifier_id);
create index if not exists leads_score_idx on nw.leads(score desc);
create index if not exists leads_available_idx on nw.leads(available_at desc) where status = 'available';
create index if not exists leads_expires_idx on nw.leads(expires_at) where status = 'available';
create index if not exists leads_phone_idx on nw.leads(phone);
create index if not exists leads_email_idx on nw.leads(email);

-- Full qualification checklist payload. One row per submitted qualification.
-- Stored as discrete columns (not jsonb) so reporting and RLS-safe filters
-- are straightforward.
create table if not exists nw.lead_qualifications (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null unique references nw.leads(id) on delete cascade,
  qualified_by uuid references nw.team_members(id),

  -- Identity & status
  visa_status text not null,                 -- citizen | permanent_resident | open_work_permit | lmia | pgwp | study_permit | refugee_claimant | other
  time_in_canada text not null,              -- under_1y | 1_2y | 2_5y | 5y_plus
  has_ab_licence boolean not null,

  -- Financial picture
  monthly_income text not null,              -- under_2k | 2k_3k | 3k_4k | 4k_5k | over_5k
  income_type text not null,                 -- employed | self_employed | benefits | multiple
  time_at_income text not null,              -- under_6m | 6m_1y | 1y_2y | over_2y
  monthly_debt text not null,                -- none | under_500 | 500_1k | over_1k

  -- Credit
  credit_score text not null,                -- under_500 | 500_580 | 580_650 | 650_plus | unknown
  active_bankruptcy boolean not null,
  discharged_bankruptcy boolean not null,
  active_consumer_proposal boolean not null,
  declined_last_6mo boolean not null,
  outstanding_collections boolean not null,

  -- Vehicle intent
  new_or_used text not null,                 -- new | used | either
  body_type text not null,                   -- suv | truck | sedan | minivan | any
  total_budget text not null,                -- under_15k | 15_20 | 20_25 | 25_30 | over_30
  monthly_payment_target text not null,      -- under_300 | 300_400 | 400_500 | over_500
  down_payment text not null,                -- none | under_1k | 1_2k | 2_5k | over_5k
  trade_in boolean not null,
  purchase_timeline text not null,           -- asap | within_2_weeks | within_month | just_browsing

  -- Logistics
  preferred_contact_time text not null,      -- morning | afternoon | evening
  preferred_language text not null,          -- english | tagalog | punjabi | hindi | arabic | french | other

  -- Optional notes (≤300 chars, enforced in app + here)
  notes text check (notes is null or char_length(notes) <= 300),

  call_duration_seconds int,                 -- for VA performance metric
  submitted_at timestamptz not null default now()
);

create index if not exists lead_quals_lead_idx on nw.lead_qualifications(lead_id);

-- Audit trail of qualifier assignments + outcomes for HR reporting.
create table if not exists nw.lead_audit_log (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references nw.leads(id) on delete cascade,
  actor_team_member_id uuid references nw.team_members(id),
  event text not null,                       -- e.g. 'assigned', 'qualified', 'marked_unqualified', 'relisted', 'sold', 'expired', 'price_updated'
  detail jsonb,
  created_at timestamptz not null default now()
);

create index if not exists lead_audit_lead_idx on nw.lead_audit_log(lead_id);
create index if not exists lead_audit_actor_idx on nw.lead_audit_log(actor_team_member_id);
create index if not exists lead_audit_event_idx on nw.lead_audit_log(event);

-- Saved buyer filters. When a new lead goes live matching any saved set,
-- the matching buyer is notified by email.
create table if not exists nw.saved_filters (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references nw.buyer_accounts(id) on delete cascade,
  name text not null,
  filters jsonb not null,                    -- {tier, body_type, budget, visa_status, down_payment, timeline, credit_bracket}
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists saved_filters_buyer_idx on nw.saved_filters(buyer_id);

-- =====================================================================
-- PURCHASES + DISPUTES
-- =====================================================================

create table if not exists nw.purchases (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null unique references nw.leads(id),
  buyer_id uuid not null references nw.buyer_accounts(id),
  sub_account_id uuid references nw.buyer_accounts(id),  -- if dealer sub purchased it

  amount_cents int not null,                 -- final captured amount
  stripe_payment_intent_id text not null unique,
  stripe_charge_id text,
  status nw.purchase_status not null default 'pending_payment',

  purchased_at timestamptz,
  failed_at timestamptz,
  failure_reason text,

  created_at timestamptz not null default now()
);

create index if not exists purchases_buyer_idx on nw.purchases(buyer_id);
create index if not exists purchases_sub_idx on nw.purchases(sub_account_id);
create index if not exists purchases_status_idx on nw.purchases(status);
create index if not exists purchases_purchased_idx on nw.purchases(purchased_at desc) where status = 'paid';

create table if not exists nw.lead_disputes (
  id uuid primary key default gen_random_uuid(),
  purchase_id uuid not null references nw.purchases(id) on delete cascade,
  lead_id uuid not null references nw.leads(id),
  buyer_id uuid not null references nw.buyer_accounts(id),

  reason text not null,                      -- e.g. 'wrong_number' | 'disconnected' | 'other'
  buyer_notes text,
  status nw.dispute_status not null default 'open',
  resolution_notes text,
  resolved_by uuid references nw.team_members(id),
  resolved_at timestamptz,

  created_at timestamptz not null default now()
);

create index if not exists lead_disputes_status_idx on nw.lead_disputes(status);
create index if not exists lead_disputes_buyer_idx on nw.lead_disputes(buyer_id);

-- Buyer credits issued from approved disputes.
create table if not exists nw.buyer_credits (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references nw.buyer_accounts(id) on delete cascade,
  amount_cents int not null,                 -- positive => credit issued, negative => credit consumed
  source text not null,                      -- 'dispute_resolution' | 'consumed_on_purchase'
  dispute_id uuid references nw.lead_disputes(id),
  purchase_id uuid references nw.purchases(id),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists buyer_credits_buyer_idx on nw.buyer_credits(buyer_id);

-- =====================================================================
-- INTERNAL EMAIL SYSTEM
-- =====================================================================

create table if not exists nw.email_threads (
  id uuid primary key default gen_random_uuid(),
  subject text not null,
  -- Lead this thread is attached to (if any). Allows team to see every email
  -- with a given lead on the lead's record.
  lead_id uuid references nw.leads(id) on delete set null,
  participant_emails citext[] not null default '{}',
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists email_threads_lead_idx on nw.email_threads(lead_id);
create index if not exists email_threads_last_msg_idx on nw.email_threads(last_message_at desc);
create index if not exists email_threads_participants_idx on nw.email_threads using gin(participant_emails);

create table if not exists nw.email_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references nw.email_threads(id) on delete cascade,
  direction nw.email_direction not null,
  from_email citext not null,
  to_emails citext[] not null,
  cc_emails citext[] not null default '{}',
  subject text not null,
  body_text text,
  body_html text,
  external_id text,                          -- Resend message id (outbound) or inbound webhook id
  -- Owning team member for outbound, or the addressed team member for
  -- inbound. Used to scope inbox visibility.
  team_member_id uuid references nw.team_members(id),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists email_messages_thread_idx on nw.email_messages(thread_id);
create index if not exists email_messages_team_idx on nw.email_messages(team_member_id);
create index if not exists email_messages_created_idx on nw.email_messages(created_at desc);

create table if not exists nw.email_attachments (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references nw.email_messages(id) on delete cascade,
  storage_path text not null,
  filename text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default now()
);

create index if not exists email_attachments_msg_idx on nw.email_attachments(message_id);

-- =====================================================================
-- VA / TEAM ACTIVITY LOGS (Outreach + Content + HR metrics)
-- =====================================================================

create table if not exists nw.outreach_logs (
  id uuid primary key default gen_random_uuid(),
  team_member_id uuid not null references nw.team_members(id) on delete cascade,
  log_date date not null default current_date,
  groups_posted_in int not null default 0,
  dms_sent int not null default 0,
  conversations_started int not null default 0,
  form_submissions_attributed int not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  unique (team_member_id, log_date)
);

create index if not exists outreach_logs_date_idx on nw.outreach_logs(log_date desc);

create table if not exists nw.content_tasks (
  id uuid primary key default gen_random_uuid(),
  team_member_id uuid not null references nw.team_members(id) on delete cascade,
  task_kind text not null,                   -- 'blog_post' | 'gbp_post' | 'copy_change' | 'directory_submission'
  title text not null,
  status text not null default 'pending',    -- 'pending' | 'in_progress' | 'completed'
  scheduled_for date,
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists content_tasks_status_idx on nw.content_tasks(status);
create index if not exists content_tasks_member_idx on nw.content_tasks(team_member_id);

create table if not exists nw.bdr_activity (
  id uuid primary key default gen_random_uuid(),
  team_member_id uuid not null references nw.team_members(id) on delete cascade,
  log_date date not null default current_date,
  dealerships_contacted int not null default 0,
  follow_ups_sent int not null default 0,
  accounts_signed int not null default 0,
  notes text,
  unique (team_member_id, log_date)
);

create index if not exists bdr_activity_date_idx on nw.bdr_activity(log_date desc);

-- Pay records per team member per period (set by HR + CEO).
create table if not exists nw.team_pay_records (
  id uuid primary key default gen_random_uuid(),
  team_member_id uuid not null references nw.team_members(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  base_pay_cents int not null default 0,
  bonus_pay_cents int not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  unique (team_member_id, period_start, period_end)
);

-- =====================================================================
-- ATTRIBUTION + COSTS (for unit economics reporting)
-- =====================================================================

create table if not exists nw.operating_costs (
  id uuid primary key default gen_random_uuid(),
  period_start date not null,
  period_end date not null,
  category text not null,                    -- 'ad_spend_facebook' | 'ad_spend_google' | 'platform' | 'payroll' | 'stripe_fees' | 'other'
  amount_cents int not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists operating_costs_period_idx on nw.operating_costs(period_start, period_end);
create index if not exists operating_costs_category_idx on nw.operating_costs(category);

-- =====================================================================
-- DAILY METRICS SNAPSHOT (for fast dashboard reads + period-over-period)
-- =====================================================================

create table if not exists nw.daily_metrics (
  metric_date date primary key,
  leads_received int not null default 0,
  leads_qualified int not null default 0,
  leads_sold int not null default 0,
  leads_expired int not null default 0,
  revenue_cents bigint not null default 0,
  avg_score smallint,
  computed_at timestamptz not null default now()
);

-- =====================================================================
-- TRIGGERS / HELPERS
-- =====================================================================

create or replace function nw.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trg_buyer_accounts_updated on nw.buyer_accounts;
create trigger trg_buyer_accounts_updated
  before update on nw.buyer_accounts
  for each row execute function nw.set_updated_at();

drop trigger if exists trg_leads_updated on nw.leads;
create trigger trg_leads_updated
  before update on nw.leads
  for each row execute function nw.set_updated_at();

-- Convenience: archive consumed/expired OTPs nightly. Pure SQL function callable
-- from a cron route so the table never grows unbounded.
create or replace function nw.purge_stale_otps()
returns int language plpgsql as $$
declare
  deleted int;
begin
  delete from nw.auth_otps
  where (consumed_at is not null and consumed_at < now() - interval '7 days')
     or expires_at < now() - interval '7 days';
  get diagnostics deleted = row_count;
  return deleted;
end $$;
